Chat:
  # use custom formatting for player messages instead of the minecraft default
  enable-custom-formatting: true

Combat:
  # Time in seconds a player is invulnerable after being hit, only whole seconds
  combat-time: 5
  can-teleport-in-combat: false

Base:
  enable: true
  # radius of the base
  range: 100
  # Whether 
  show-particles: true
  # Whether to disable bombs dropped in the base
  # Also includes airstrikes
  bomb-protection: true
  protect-from-napalm: false
  # Whether to disable block breaking for other teams in the base
  disable-block-breaking: false
  # Whether to disable block placing for other teams in the base
  disable-block-placing: false
  # Whether to disable block interaction for other teams in the base
  disable-block-interacting: true
  # Whether to disable creepers spawning in the base
  prevent-creeper-spawn: true


Turret:
  # this will also enable the rocket launcher
  enable: true
  # whether to check team of player before shooting
  # if false, the turret will shoot at any player and any player can interact with the turret
  check-team: true
  # Default value for the shot delay when placed, can be changed in the turret menu
  shot-delay: 3
  min-shot-delay: 1
  max-shot-delay: 5
  particle-delay: 0
  glowing-arrow: true
  # The number of particles each arrow spawns per tick
  particle-amount: 10
  particle-spread: 0.4
  reach: 192
  damage: 0.5
  arrow-speed-multiplier: 5
  # Tick delay between player distance checks
  distance-check-delay: 20
  # Tick delay between performance checks (automatically disable turret tasks if no player is online etc.)
  performance-check-delay: 600
  # whether the arrow is burning or not
  burning-arrow: false
  # whether the turret makes noise when shooting
  silenced: false

SmokeGrenade:
  enable: true
  # Particle amount will be calculated based on the radius, too high values will not look good as there is a particle limit for clients
  radius: 4.0
  # Cooldown in ticks between smoke grenade throws
  cooldown: 100

PlayerMounting:
  enable: true
  # Reach and damage of the M2 Browning the gunman gets when mounted
  canon-reach: 100.0
  canon-damage: 5.0
  # whether to prevent players from mounting on players who aren't flying
  # players have 5 seconds to take off before being dismounted if this is set to true
  only-flight: true
  # whether to play a hurt animation when shooting
  hurt-animation: false
  # The time in ticks a player has before being dismounted when the plane isn't flying
  dismount-time: 100

Airstrike:
  enable: true
  missile-amount: 6
  # delay in ticks between each missile
  missile-delay: 8
  # explosion force of a missile
  missile-yield: 10
  # delay in ticks between the arrow hitting the ground and the first missile being spawned
  initial-delay: 60

Bomb:
  enable-small: true
  enable-medium: true
  enable-large: true
  # The yield of the bomb explosion
  # Usually a server can handle a couple of 150 yield bombs at once, but after that it starts to lag pretty soon
  small-yield: 6
  medium-yield: 15
  large-yield: 100
  
  drop-ammonium-nitrate: true
  drop-plutonium: true
  
  # The chance of a creeper dropping ammonium nitrate (1/x)
  ammonium-nitrate-chance: 20
  # The chance of a creeper dropping plutonium (1/x)
  plutonium-chance: 200
  
  # The maximum speed a player is allowed to fly if he is carrying a certain bomb
  small-speed-limit: 0.8
  medium-speed-limit: 0.6
  large-speed-limit: 0.4

  # Time in ticks before the bomb explodes after being dropped
  fuse-ticks: 100

MANPAD:
  enable: true
  # The range of the MANPAD (in blocks)
  range: 125.0
  # The speed of the missile
  speed: 4.0
  # The explosion force of the missile
  yield: 3.0
  # Lifetime of the missile in ticks
  lifetime: 80
  # The time in ticks the player has to look at the target before the missile locks on
  lock-on-time: 35
  # The cooldown in ticks for the MANPAD
  cooldown: 100
  # The angle in degrees the player's aim can be off
  lock-angle-threshold: 10.0

Napalm:
  enable: true
  # The number of missiles spawned
  amount: 20
  # The delay in ticks between each missile
  delay: 2
  # The ignition radius of each missile
  radius: 2

RocketLauncher:
  # is enabled and disabled together with the turret
  range: 125.0
  # Explosion force of the rocket
  yield: 2.0

Other:
  # enable /tpa command
  enable-tpa: false
  # enable /spawn command
  enable-spawn: false
  # enable /base command (tp to base)
  enable-base-tp: true
  # enable /join command (request to join a team)
  enable-join: true