Combat:
  # only whole seconds
  combat-time: 5
  can-teleport-in-combat: false

Turret:
  shot-delay: 3
  particle-delay: 0
  particle-amount: 10
  particle-spread: 0.1
  reach: 500
  damage: 0.5
  arrow-speed-multiplier: 5
  # Tick delay between player distance checks
  player-check-delay: 20