name: CustomPlugin
version: '${project.version}'
main: me.kehessen.customplugin.CustomPlugin
api-version: '1.20'
authors: [ Kenny ]
commands:
  announce:
    description: Announce a message
    usage: /announce <message>
    permission: op
  tpa:
    description: Send a teleport request to a player
  tpaccept:
    description: Accept a teleport request
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  combattime:
    description: Check someone's combat time
    usage: /combattime <player>
    permission: op
  turret:
    description: turret options
    usage: /turret <spawn/remove/reload/silence/burningArrow/targets/shotDelay/disableAll/enableAll/getEnderPearl/give>
    permission: op
  bomb:
    description: tnt options
    usage: /tnt <spawn> <yield>
    permission: op
  mount:
    description: mount a player to act as a shooter
    usage: /mount <player>
  customitem:
    description: give a custom item
    usage: /customitem <item>
    permission: op