name: Icarus
version: '${project.version}'
main: me.kehessen.icarus.Icarus
api-version: '1.21'
author: kehessen
website: https://github.com/kehessen/Icarus/
commands:
  tpa:
    description: Send a teleport request to a player
  tpaccept:
    description: Accept a teleport request
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  base: 
    description: Teleport to base
    usage: /base
  bomb:
    description: bomb options
    usage: /bomb <spawn> <yield>
    permission: op
  mount:
    description: mount a player to act as a shooter
    usage: /mount <player>
  icarusitem:
    description: give a custom item
    usage: /icarusitem <item>
    permission: op
  join:
    description: join a team
    usage: /join <team>
  accept:
    description: accept a team invite
    usage: /accept <player>
  decline:
    description: decline a team invite
    usage: /decline <player>