name: CustomPlugin
version: '${project.version}'
main: me.kehessen.customplugin.CustomPlugin
api-version: '1.20'
authors: [ Kenny ]
commands:
  announce:
    description: Announce a message
    usage: /announce <message>
    permission: op
  tpa:
    description: Teleport to a player
  tpaccept:
    description: Accept a teleport request
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  combattime:
    description: Check someone's combat time
    usage: /combattime <player>
    permission: op
  test:
    description: Test command
    usage: /test
    permission: op
  turret:
    description: turret options
    usage: /turret <spawn/remove/reload/silence/burningArrow/targets/shotDelay>
    permission: op
  lasercanon:
    description: lasercanon options
    usage: /lasercanon <spawn/remove/reload/silence>
    permission: op