name: Icarus
version: '${project.version}'
main: me.kehessen.icarus.Icarus
api-version: '1.21'
author: Kenny
website: https://github.com/kehessen/Icarus/
commands:
  announce:
    description: Announce a message
    usage: /announce <message>
    permission: op
  tpa:
    description: Send a teleport request to a player
  tpaccept:
    description: Accept a teleport request
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  base: 
    description: Teleport to base
    usage: /base
  combattime:
    description: Check someone's combat time
    usage: /combattime <player>
    permission: op
  turret:
    description: turret options
    usage: /turret <spawn/remove/reload/silence/burningArrow/targets/shotDelay/disableAll/enableAll/getEnderPearl/give>
    permission: op
  bomb:
    description: tnt options
    usage: /tnt <spawn> <yield>
    permission: op
  mount:
    description: mount a player to act as a shooter
    usage: /mount <player>
  icarusitem:
    description: give a custom item
    usage: /customitem <item>
    permission: op
  join:
    description: join a team
    usage: /join <team>
  accept:
    description: accept a team invite
    usage: /accept <player>
  decline:
    description: decline a team invite
    usage: /decline <player>