name: Icarus
version: '${project.version}'
main: me.kehessen.icarus.Icarus
api-version: '26.1'
author: kehessen
website: https://github.com/kehessen/Icarus/
commands:
  tpa:
    description: Send a teleport request to a player
  tpaccept:
    description: Accept a teleport request
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  base: 
    description: Teleport to base
    usage: /base
  bomb:
    description: Bomb options
    usage: /bomb <spawn> <yield>
    permission: op
  icarusitem:
    description: Give a custom item
    usage: /icarusitem <item>
    permission: op
  join:
    description: Send a request to join a team
    usage: /join <team>
  accept:
    description: Accept a team invite
    usage: /accept <player>
  decline:
    description: Decline a team invite
    usage: /decline <player>