name: CustomPlugin
version: '${project.version}'
main: me.kehessen.customplugin.CustomPlugin
api-version: '1.20'
authors: [ Kenny ]
commands:
  announce:
    description: Announce a message
    usage: /announce <message>
    permission: op
  tpa:
    description: Teleport to a player
  tpaccept:
    description: Accept a teleport request
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  combattime:
    description: Check someone's combat time
    usage: /combattime <player>
    permission: op

  turret:
    description: Spawn a turret shooting arrows
    usage: /turret <spawn/remove/reload/silence/burningArrow>
    permission: op
  spawnparticleturret:
    description: Spawn a turret shooting particles
    usage: /spawnparticleturret
    permission: op
  removeallparticleturrets:
    description: Remove all particle turrets
    usage: /removeallparticleturrets
    permission: op